### ISSUE TITLE
Questions on Dockerfile installs

### ISSUE THREAD

**Issue by daxm** [jhpyle/docassemble-os#4]
I'm working on "cleaning up", mostly formatting, the Dockerfile but I have questions on whether all these apt-get installs are necessary.

For example, is nginx and apache2 needed?  perl?

I don't want to reinvent but I can imagine this file could be cleaned up.

Would you mind providing me justification for the list items?  I'd love to reduce the MASSIVE size this image ends up being.

**Comment by jhpyle** [comment]
The image is large because it contains a full TeX Live implementation. Almost everything else is relatively tiny.

Apache used to be the default web server before I changed the default to NGINX. I kept Apache around for backwards compatibility reasons in case people had been using Apache with custom web server configurations. https://docassemble.org/docs/config.html#web%20server

The Google Fonts installation (the download from `https://github.com/google/fonts/archive/main.tar.gz`) significantly increases the size of the image. Perhaps that isn't necessary, but people want to have different fonts available.

Much of the perl-related stuff comes from the need to convert audio files (`pacpl`) and that is also why `ffmpeg` is there.

Many of the Debian packages were added to the list because a Python package will not install unless a supporting C library is present.

The image could be made smaller by removing features from the software, particularly the Pandoc document assembly feature.

**Comment by daxm** [comment]
If they are needed they are needed!  I'll work with that.  :-)

I'm new to docassemble to I won't know how to test if my "cleanup" will affect the outcome but I'm going to try to at least make the file more readable.

As an aside, have you considered splitting some services out to different Docker containers and using docker-compose to orchestrate the containers?  I notice  several services that could probably run on standalone containers (many of which might work using that service's publish image.  I'm looking at redis and rabbitmq.

**Comment by jhpyle** [comment]
I haven't used docker compose but there is a Helm chart that does that. See https://docassemble.org/docs/scalability.html#kubernetes.

**Comment by daxm** [comment]
Issued a PR with "improved" Dockerfile options.

**Comment by BryceStevenWilley** [comment]
For what it's worth, I have a [personal branch of docassemble](https://github.com/BryceStevenWilley/docassemble/blob/smol/Dockerfile) where I stripped out a lot of these extra services that we weren't using, and [published it to docker hub](https://hub.docker.com/r/brycewilley/smoldocassemble). It's definitely not usable for production, but it's nice for more quickly spinning up testing containers.
